-- 建立 numbers 表
CREATE TABLE IF NOT EXISTS public.numbers (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    value integer NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

-- 開啟 Row Level Security (RLS)
ALTER TABLE public.numbers ENABLE ROW LEVEL SECURITY;

-- 建立 Policy 允許匿名角色 (anon) 進行 Insert (使用者輸入頁)
CREATE POLICY "Allow anonymous insert" ON public.numbers
    FOR INSERT WITH CHECK (true);

-- 建立 Policy 允許匿名角色 (anon) 進行 Select (後台管理頁讀取，並允許 Realtime 訂閱)
CREATE POLICY "Allow anonymous select" ON public.numbers
    FOR SELECT USING (true);

-- 為了讓 Supabase Realtime 起作用，需要啟用該表的 replication
alter publication supabase_realtime add table public.numbers;
